
from PyQt5.QtWidgets import QMainWindow, QApplication, QAction,QDateEdit, QTableWidget,QTableWidgetItem,QVBoxLayout
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import pyqtSlot
from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import *
import tkinter.messagebox
import pyodbc
import hasta_silme
import os
class Ui_MainWindow(object):
    def show_patients(self):
        try:
            conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=SELIM\SQLSCA;'
                      'Database=hastane;'
                      'Trusted_Connection=yes;')
            cursor = conn.cursor()  
            cursor.execute('SELECT * FROM hastane.dbo.users')       
            self.tableWidget.setRowCount(20)
            self.tableWidget.setColumnCount(3)
            self.tableWidget.setColumnWidth
            records = cursor.fetchall()
            a=1
            b=0
            self.tableWidget.clear()
            for row in records:
                self.tableWidget.setItem(0,0, QTableWidgetItem("Username"))
                self.tableWidget.setItem(0,1, QTableWidgetItem("Password"))
                self.tableWidget.setItem(0,2, QTableWidgetItem("Yetki"))
                self.tableWidget.setItem(a,b, QTableWidgetItem(str(row[1])))
                self.tableWidget.setItem(a,b+1, QTableWidgetItem(row[2]))
                self.tableWidget.setItem(a,b+2, QTableWidgetItem(row[3]))
        
                a=a+1
                conn.commit()
        finally:
            if (conn):
                conn.close()    
    def user_ekleme(self): 
        username=self.usernameadd.text()
        sifre=self.sifreadd.text()
        yetki=self.yetkiadd.currentText()

        conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=SELIM\SQLSCA;'
                      'Database=hastane;'
                      'Trusted_Connection=yes;')

        cursor = conn.cursor()
        cursor.execute('''
                INSERT INTO hastane.dbo.users (username,pass,yetki)VALUES ('%s','%s','%s') '''%(username,sifre,yetki))
        conn.commit()                 
    def bilgi_getir(self):
        username=self.usernameguncelle.text()
        conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=SELIM\SQLSCA;'
                      'Database=hastane;'
                      'Trusted_Connection=yes;')
        cursor = conn.cursor()  
        cursor.execute("""SELECT * FROM hastane.dbo.users WHERE username='%s'"""%(username))       
        records = cursor.fetchall()
        for row in records:
            self.usernameguncelle.setText(row[1])
            self.sifreadd_2.setText(row[2])
    def user_guncelleme(self): 
        username=self.usernameguncelle.text()
        sifre=self.sifreadd_2.text()
        yetki=self.usernameyetki.currentText()

        conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=SELIM\SQLSCA;'
                      'Database=hastane;'
                      'Trusted_Connection=yes;')

        cursor = conn.cursor()
        cursor.execute('''

                UPDATE hastane.dbo.users SET username=?,pass =?,yetki=? WHERE username=? ''',username,sifre,yetki,username)
        conn.commit() 
    def user_sil(self):
        username = self.usernamesil.text()   
        conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=SELIM\SQLSCA;'
                      'Database=hastane;'
                      'Trusted_Connection=yes;')

        cursor = conn.cursor()
        cursor.execute('''

                DELETE FROM users where username = '%s'
                '''%(username))
        conn.commit()
    def temizle(self):
        self.usernameadd.clear()
        self.sifreadd.clear()
    def eklendiGoster(self,MainWindow):
        root = tkinter.Tk()
        root.withdraw()
        exit = tkinter.messagebox.showinfo("Bilgi","Yeni Kullanıcı Eklendi")
    def silindiGoster(self,MainWindow):
        root = tkinter.Tk()
        root.withdraw()
        exit = tkinter.messagebox.showinfo("Bilgi","Kullanıcı Silindi")     
    def guncellendiGoster(self,MainWindow):
        root = tkinter.Tk()
        root.withdraw()
        exit = tkinter.messagebox.showinfo("Bilgi"," Kullanıcı Güncellendi")     

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 530)
        MainWindow.setMinimumSize(QtCore.QSize(710, 530))
        MainWindow.setMaximumSize(QtCore.QSize(710, 530))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 271, 154))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.usernameadd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameadd.setMinimumSize(QtCore.QSize(0, 25))
        self.usernameadd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.usernameadd.setBaseSize(QtCore.QSize(0, 0))
        self.usernameadd.setObjectName("usernameadd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameadd)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sifreadd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sifreadd.setMinimumSize(QtCore.QSize(0, 25))
        self.sifreadd.setObjectName("sifreadd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sifreadd)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.yetkiadd = QtWidgets.QComboBox(self.formLayoutWidget)
        self.yetkiadd.setMinimumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.yetkiadd.setFont(font)
        self.yetkiadd.setObjectName("yetkiadd")
        self.yetkiadd.addItem("")
        self.yetkiadd.addItem("")
        self.yetkiadd.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yetkiadd)
        self.eklebutton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.eklebutton.setMinimumSize(QtCore.QSize(25, 30))
        self.eklebutton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eklebutton.setFont(font)
        self.eklebutton.setObjectName("eklebutton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eklebutton)
        self.eklebutton_4 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.eklebutton_4.setMinimumSize(QtCore.QSize(25, 30))
        self.eklebutton_4.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eklebutton_4.setFont(font)
        self.eklebutton_4.setObjectName("eklebutton_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.eklebutton_4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 30, 271, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(350, 30, 271, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(350, 50, 271, 71))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.usernamesil = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.usernamesil.setMinimumSize(QtCore.QSize(0, 25))
        self.usernamesil.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.usernamesil.setBaseSize(QtCore.QSize(0, 0))
        self.usernamesil.setObjectName("usernamesil")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernamesil)
        self.silbutton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.silbutton.setMinimumSize(QtCore.QSize(25, 30))
        self.silbutton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.silbutton.setFont(font)
        self.silbutton.setObjectName("silbutton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.silbutton)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(350, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 250, 271, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 270, 271, 181))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.usernameguncelle = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.usernameguncelle.setMinimumSize(QtCore.QSize(0, 25))
        self.usernameguncelle.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.usernameguncelle.setBaseSize(QtCore.QSize(0, 0))
        self.usernameguncelle.setObjectName("usernameguncelle")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameguncelle)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.sifreadd_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.sifreadd_2.setMinimumSize(QtCore.QSize(0, 25))
        self.sifreadd_2.setObjectName("sifreadd_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sifreadd_2)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.usernameyetki = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.usernameyetki.setMinimumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.usernameyetki.setFont(font)
        self.usernameyetki.setObjectName("usernameyetki")
        self.usernameyetki.addItem("")
        self.usernameyetki.addItem("")
        self.usernameyetki.addItem("")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameyetki)
        self.eklebutton_2 = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.eklebutton_2.setMinimumSize(QtCore.QSize(25, 30))
        self.eklebutton_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eklebutton_2.setFont(font)
        self.eklebutton_2.setObjectName("eklebutton_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eklebutton_2)
        self.eklebutton_3 = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.eklebutton_3.setMinimumSize(QtCore.QSize(25, 30))
        self.eklebutton_3.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eklebutton_3.setFont(font)
        self.eklebutton_3.setObjectName("eklebutton_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.eklebutton_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 230, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(320, 181, 341, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(320, 160, 131, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(320, 140, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.eklebutton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.eklebutton_5.setGeometry(QtCore.QRect(470, 140, 100, 30))
        self.eklebutton_5.setMinimumSize(QtCore.QSize(100, 30))
        self.eklebutton_5.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.eklebutton_5.setFont(font)
        self.eklebutton_5.setObjectName("eklebutton_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 761, 541))
        self.frame.setStyleSheet("background-color: rgb(70, 169, 135);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.formLayoutWidget.raise_()
        self.label_4.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.formLayoutWidget_2.raise_()
        self.label_8.raise_()
        self.line_3.raise_()
        self.formLayoutWidget_3.raise_()
        self.label_10.raise_()
        self.tableWidget.raise_()
        self.line_4.raise_()
        self.label_11.raise_()
        self.eklebutton_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yetkilendirme Sayfası"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Şifre"))
        self.label_3.setText(_translate("MainWindow", "Yetki"))
        self.yetkiadd.setItemText(0, _translate("MainWindow", "Admin"))
        self.yetkiadd.setItemText(1, _translate("MainWindow", "DataReader"))
        self.yetkiadd.setItemText(2, _translate("MainWindow", "DataWriter"))
        self.eklebutton.setText(_translate("MainWindow", "Ekle"))
        self.eklebutton_4.setText(_translate("MainWindow", "Temizle"))
        self.label_4.setText(_translate("MainWindow", "Yönetici Ekle"))
        self.label_5.setText(_translate("MainWindow", "Username"))
        self.silbutton.setText(_translate("MainWindow", "Sil"))
        self.label_8.setText(_translate("MainWindow", "Yönetici Sil"))
        self.label_6.setText(_translate("MainWindow", "Username"))
        self.label_7.setText(_translate("MainWindow", "Şifre"))
        self.label_9.setText(_translate("MainWindow", "Yetki"))
        self.usernameyetki.setItemText(0, _translate("MainWindow", "Admin"))
        self.usernameyetki.setItemText(1, _translate("MainWindow", "DataReader"))
        self.usernameyetki.setItemText(2, _translate("MainWindow", "DataWriter"))
        self.eklebutton_2.setText(_translate("MainWindow", "Güncelle"))
        self.eklebutton_3.setText(_translate("MainWindow", "Getir"))
        self.label_10.setText(_translate("MainWindow", "Yönetici Güncelle"))
        self.label_11.setText(_translate("MainWindow", "Yönetici Listesi"))
        self.eklebutton_5.setText(_translate("MainWindow", "Listele"))
# buton clickleri
        self.eklebutton_5.clicked.connect(self.show_patients)
        self.eklebutton.clicked.connect(self.user_ekleme)
        self.eklebutton_3.clicked.connect(self.bilgi_getir)
        self.eklebutton_2.clicked.connect(self.user_guncelleme)
        self.silbutton.clicked.connect(self.user_sil)
        self.eklebutton_4.clicked.connect(self.temizle)
        self.eklebutton.clicked.connect(self.eklendiGoster)
        self.eklebutton.clicked.connect(self.show_patients)
        self.eklebutton_2.clicked.connect(self.show_patients)
        self.silbutton.clicked.connect(self.show_patients)
        self.eklebutton_2.clicked.connect(self.guncellendiGoster)
        self.silbutton.clicked.connect(self.silindiGoster)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
